### ISSUE TITLE
regulator download not working

### ISSUE THREAD

**Issue by arendma** [arendma/GRN_web#51]
When pressing the button to download a table of predicted regulators, no download is started.

**Comment by arne-cl** [comment]
This is about the download button `Top coregulators in consensus network:` in the `Top coregulators` tab:

![image](https://github.com/arendma/GRN_web/assets/994109/a050d5a2-8517-47de-9a24-44cc059e36f7)

The download button links to `http://grn-web.bio.uni-potsdam.de/session/55300aa64482aaf68453e056a2658f01/download/downloadCoregs?w=` and on click opens an empty new tab.

**Comment by arne-cl** [comment]
Fixed by #52 and deployed on the server.
